### ISSUE TITLE
Write unit tests for SPADE

### ISSUE THREAD

**Issue by mdenker** [INM-6/elephant#13]
Decision was made to have one test module for everything SPADE-related.

Note: The unit tests should cover a test case checking for equivalence of all implementations of FIM!

**Comment by mdenker** [comment]
@pietroquaglio, could you give a quick update on the status of this issue?

**Comment by pietroquaglio** [comment]
@mdenker : biggest part of the unit tests are written with a coverage ~80%. I wanted to finish to cover few corner cases. In general SPADE is basically ready for the pull request, I just need to finish some documentation, change the licensing and clean up a bit Dominik's code

**Comment by mdenker** [comment]
@pietroquaglio Thanks for the update, that sounds great!
