### ISSUE TITLE
Create wiki entry 'How to contribute to elephant'

### ISSUE THREAD

**Issue by JuliaSprenger** [INM-6/elephant#22]

**Comment by alperyeg** [comment]
Have a look at the [enh/clean_ue branch](https://github.com/INM-6/elephant/tree/enh/clean_ue), especially [doc_style_guidelines.rst](https://github.com/INM-6/elephant/blob/enh/clean_ue/doc/doc_style_guidelines.rst)

**Comment by Moritz-Alexander-Kern** [comment]
We have a section on "how to contribute" in the documentation:

https://elephant.readthedocs.io/en/latest/contribute.html
