### ISSUE TITLE
bug in the spike_train_surrogates module

### ISSUE THREAD

**Issue by Vahidrostami** [INM-6/elephant#4]
@etorre  
`isi_shuffling` function in the spike_train_surrogates module does not perform correctly in the two cases below:
1- when the given spike train is not sorted in an increasing order
2- sometimes the last spike of generated surrogates is larger than t_stop of original spike train. This I did not figure out yet when it exactly happens, but it happens!

**Comment by alperyeg** [comment]
A regression test would be appropriate, to indicate the bug and also to test it in the unittests.
