### ISSUE TITLE
Add Rescience paper as unit test for Unitary Events

### ISSUE THREAD

**Issue by mdenker** [INM-6/elephant#59]
The unitary events implementation in Elephant was validated against the original publication of 1997 in
https://github.com/ReScience-Archives/Rostami-Ito-Denker-Gruen-2017
Parts of this validation should be integrated as unit test into Elephant. One possibility would be to load the original UE time stamps from a file, and compare them to the output of the unitary_events function.

**Comment by mdenker** [comment]
@Vahidrostami Hi, have you had the chance to make any progress on this issue? Could I be of help?

**Comment by Vahidrostami** [comment]
@mdenker I just sent a PR (#152)

**Comment by Moritz-Alexander-Kern** [comment]
Done : https://github.com/NeuralEnsemble/elephant/pull/152
