### ISSUE TITLE
Update README.rst

### ISSUE THREAD

**Issue by alperyeg** [INM-6/elephant#66]
The `README.rst` file contains only links and a short description so far. It should rather contain a description on how to install Elephant and give some more information about Elephant usage. It may sound rather redundant since we have a readthedocs page but on the other hand this can help a new user to have quick glance over the Elephant package. 

Topics we can include into the `README.rst`
* Elephant # general information, we have that already
* Quick description # focus of the package, what is it for
*  Use cases # optional, could mention the HBP
* Quick setup # pip stuff, and other ways to install
* Help and support # where to find the documentation, whom to contact, how to make a issue etc., (citation), authors

**Comment by mdenker** [comment]
Most of these things were integrated into the README.
