### ISSUE TITLE
check compatibility with neo 0.7

### ISSUE THREAD

**Issue by JuliaSprenger** [INM-6/elephant#67]
There were some changes in neo, which elephant is not taking into account yet.
Eg `AnalogSignals` don't have a method `duplicate_with_new_array` anymore but `duplicate_with_new_data` to be more consistent with other Neo objects. This affects elephant eg here: https://github.com/INM-6/elephant/blob/c6ffc3b2a589b6b44f6c193b64052e201d9b034a/elephant/signal_processing.py#L379

**Comment by JuliaSprenger** [comment]
maybe this issue rather belongs to https://github.com/NeuralEnsemble/elephant?

**Comment by kkorvasova** [comment]
See https://github.com/NeuralEnsemble/elephant/issues/195
